baseurl = ""
languageCode = "ja"
title = "eichann's blog"
author = "rakuishi"

[params]
  logo      = "/images/logo.jpg"
  copyright = "eichann All rights reserved."
  twitter   = "https://twitter.com/abkin401"
  facebook  = "https://www.facebook.com/koichiro.abe.14"
  github    = "https://github.com/eichann/"
  email     = "k.abe.in401@gmail.com"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
